version: '3.4'

networks:
  dev:
    driver: bridge

volumes:
  app_data:

services:
  rabbitmq.service:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  appynox.consul:
    image: "hashicorp/consul:latest"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - dev

  appynox.gateway.ocelotgateway:
    image: ${DOCKER_REGISTRY-}appynoxgatewayocelotgateway
    build:
      context: .
      dockerfile: src/Gateways/AppyNox.Gateway.OcelotGateway/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_URLS=https://+:7000
    volumes:
     - ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl:/https
     - ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/crt:/usr/local/share/ca-certificates/
    ports:
     - "7000:7000"
    networks:
      - dev

  authentication.db:
    image: postgres:latest
    environment:
      POSTGRES_DB: AppyNox_Authentication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth_password
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - app_data:/var/lib/authenticationdb/data
    networks:
      - dev

  appynox.services.authentication.webapi:
    image: ${DOCKER_REGISTRY-}appynoxservicesauthenticationwebapi
    build:
      context: .
      dockerfile: src/Services/AuthenticationService/AppyNox.Services.Authentication.WebAPI/Dockerfile
    depends_on:
       authentication.db:
          condition: service_started
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_URLS=https://+:7001
    volumes:
     - ./src/Services/AuthenticationService/AppyNox.Services.Authentication.WebAPI/ssl:/https
     - ./src/Services/AuthenticationService/AppyNox.Services.Authentication.WebAPI/ssl/crt:/usr/local/share/ca-certificates/
    ports:
     - "7001:7001"
    networks:
     - dev

  coupon.db:
    image: postgres:latest
    environment:
      POSTGRES_DB: AppyNox_Coupon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coupon_password
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - app_data:/var/lib/coupondb/data
    networks:
      - dev

  appynox.services.coupon.webapi:
    image: ${DOCKER_REGISTRY-}appynoxservicescouponwebapi
    build:
      context: .
      dockerfile: src/Services/CouponService/AppyNox.Services.Coupon.WebAPI/Dockerfile
    depends_on:
       coupon.db:
          condition: service_started
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_URLS=https://+:7002
    volumes:
     - ./src/Services/CouponService/AppyNox.Services.Coupon.WebAPI/ssl:/https
     - ./src/Services/CouponService/AppyNox.Services.Coupon.WebAPI/ssl/crt:/usr/local/share/ca-certificates/
    ports:
     - "7002:7002"
    networks:
     - dev

