version: '3.8'

volumes:
  app_data:

services:
  appynox-rabbitmq-service:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: on-failure

  appynox-consul:
    image: "hashicorp/consul:latest"

  appynox-gateway-ocelotgateway:
    image: ${DOCKER_REGISTRY-}appynoxgatewayocelotgateway
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_URLS=https://+:7000
    depends_on:
        - appynox-consul
    volumes:
     - ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl:/https
     - ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/crt:/usr/local/share/ca-certificates/
    ports:
     - "443:7000"

  appynox-authentication-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: AppyNox_Authentication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth_password
    volumes:
      - app_data:/var/lib/authenticationdb/data

  appynox-services-authentication-webapi:
    image: ${DOCKER_REGISTRY-}appynoxservicesauthenticationwebapi
    depends_on:
        - appynox-consul
        - appynox-authentication-db
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_URLS=http://+:7001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  appynox-coupon-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: AppyNox_Coupon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coupon_password
    volumes:
      - app_data:/var/lib/coupondb/data

  appynox-services-coupon-webapi:
    image: ${DOCKER_REGISTRY-}appynoxservicescouponwebapi
    depends_on:
        - appynox-consul
        - appynox-coupon-db
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_URLS=http://+:7002
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro