version: '3.8'

volumes:
  rabbitmq_data: 
  consul_data: 
  redis_data: 
  redisinsight_data: 
  sso_db_data: 
  sso_saga_db_data: 
  coupon_db_data: 
  license_db_data: 


services:
  appynox-rabbitmq-service:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command:
      [
        "bash",
        "-c",
        "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"
      ]
    restart: on-failure

  appynox-consul:
    image: "hashicorp/consul:latest"

  appynox-redis:
    image: redis:latest
    volumes:
      - redis_data:/data
      - ./redis.acl:/etc/redis/redis.acl
    command: ["redis-server", "--aclfile", "/etc/redis/redis.acl"] 

  appynox-redisinsight:
    image: redislabs/redisinsight
    volumes:
      - redisinsight_data:/db

  appynox-gateway-ocelotgateway:
    image: ${DOCKER_REGISTRY-}appynoxgatewayocelotgateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443
    depends_on:
      - appynox-consul
    volumes:
      - ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl:/https2:ro
      - ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/crt:/usr/local/share/ca-certificates/:ro
    ports:
      - "7000:443"

  appynox-sso-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: AppyNox_Sso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth_password
    volumes:
      - sso_db_data:/var/lib/ssodb/data

  appynox-sso-saga-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: AppyNox_Sso_Saga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth_saga_password
    volumes:
      - sso_saga_db_data:/var/lib/ssodb/data

  appynox-services-sso-webapi:
    image: ${DOCKER_REGISTRY-}appynoxservicesssowebapi
    depends_on:
      - appynox-rabbitmq-service
      - appynox-consul
      - appynox-sso-db
      - appynox-sso-saga-db
      - appynox-redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7001
      - WAIT_HOSTS=appynox-sso-db:5432,appynox-sso-saga-db:5432,appynox-rabbitmq-service:5672
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  appynox-coupon-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: AppyNox_Coupon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coupon_password
    volumes:
      - coupon_db_data:/var/lib/coupondb/data

  appynox-services-coupon-webapi:
    image: ${DOCKER_REGISTRY-}appynoxservicescouponwebapi
    depends_on:
      - appynox-consul
      - appynox-coupon-db
      - appynox-redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7002
      - WAIT_HOSTS=appynox-coupon-db:5432
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  appynox-license-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: AppyNox_License
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: license_password
    volumes:
      - license_db_data:/var/lib/licensedb/data

  appynox-services-license-webapi:
    image: ${DOCKER_REGISTRY-}appynoxserviceslicensewebapi
    depends_on:
      - appynox-consul
      - appynox-license-db
      - appynox-redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7003
      - WAIT_HOSTS=appynox-license-db:5432
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
