volumes:
  rabbitmq_data:
  common_rabbitmq_data:
  consul_data:
  redis_data:
  redisinsight_data:
  seq_data:

networks:
  nox_network:
    driver: bridge

services:
  appynox-rabbitmq-service:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: HappiCorp
      RABBITMQ_DEFAULT_PASS: HappiCorp
    command: >
      bash -c "chmod 400 /var/lib/rabbitmq/.erlang.cookie && rabbitmq-server"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nox_network
    restart: on-failure


  appynox-common-rabbitmq-service:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: NoxFleetComm
      RABBITMQ_DEFAULT_PASS: NoxFleetComm
    command: >
      bash -c "chmod 400 /var/lib/rabbitmq/.erlang.cookie && rabbitmq-server"
    volumes:
      - common_rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672" 
    networks:
      - nox_network 
    restart: on-failure


  appynox-consul:
    image: "hashicorp/consul:latest"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - nox_network
    restart: on-failure


  appynox-redis:
    image: redis:latest
    command: ["redis-server", "--aclfile", "/etc/redis/redis.acl"] 
    volumes:
      - redis_data:/data
      - ./redis.acl:/etc/redis/redis.acl
    ports:
      - "6379:6379"
    networks:
      - nox_network
    restart: on-failure


  appynox-redisinsight:
    image: redis/redisinsight:latest
    volumes:
      - redisinsight_data:/db
    ports:
      - "6999:8001"

  appynox-seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq_data:/data
    ports:
      - "5341:5341"
      - "8081:80"
    networks:
      - nox_network
    restart: on-failure 