networks:
  nox_network:
    driver: overlay
  nox_common_network:
    external: true

services:
  appynox-rabbitmq-service:
      environment:
        RABBITMQ_DEFAULT_USER: HappiCorp
        RABBITMQ_DEFAULT_PASS: HappiCorp
      ports:
        - "15672:15672"
      networks:
        - nox_network
      restart: always


  appynox-common-rabbitmq-service:
      environment:
        RABBITMQ_DEFAULT_USER: NoxFleetComm
        RABBITMQ_DEFAULT_PASS: NoxFleetComm
      ports:
        - "15673:15672"
      networks:
        - nox_common_network
      restart: always


  appynox-consul:
    networks:
      - nox_network
    ports:
      - "8500:8500" 
    restart: always


  appynox-redis:
    networks:
      - nox_network
    restart: always


  appynox-redisinsight:
    networks:
      - nox_network
    ports:
      - "6999:8001"
    restart: always


  appynox-seq:
    networks:
      - nox_network
    restart: always


  appynox-gateway-ocelotgateway:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - nox_network


  appynox-sso-db:
    ports:
      []
    networks:
      - nox_network


  appynox-sso-saga-db:
    ports:
      []
    networks:
      - nox_network


  appynox-services-sso-webapi:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      [] 
    networks:
      - nox_network


  appynox-coupon-db:
    ports:
      []
    networks:
      - nox_network


  appynox-services-coupon-webapi:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      [] 
    networks:
      - nox_network


  appynox-license-db:
    ports:
      []
    networks:
      - nox_network


  appynox-services-license-webapi:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      [] 
    networks:
      - nox_network