version: '3.8'

networks:
  nox_network:
    driver: overlay

services:
  appynox-rabbitmq-service:
    environment:
      RABBITMQ_DEFAULT_USER: HappiCorp
      RABBITMQ_DEFAULT_PASS: HappiCorp
    networks:
      - nox_network

  appynox-consul:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - nox_network

  appynox-redis:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - nox_network

  appynox-redisinsight:
    image: redislabs/redisinsight
    networks:
      - nox_network
    ports:
      - "8001:8001"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  appynox-gateway-ocelotgateway:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - nox_network

  appynox-sso-db:
    networks:
      - nox_network

  appynox-sso-saga-db:
    networks:
      - nox_network

  appynox-services-sso-webapi:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - nox_network

  appynox-coupon-db:
    networks:
      - nox_network

  appynox-services-coupon-webapi:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - nox_network

  appynox-license-db:
    networks:
      - nox_network

  appynox-services-license-webapi:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - nox_network
