// <auto-generated />
using System;
using AppyNox.Services.Sso.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppyNox.Services.Sso.Infrastructure.Migrations.IdentitySagaDatabase
{
    [DbContext(typeof(IdentitySagaDatabaseContext))]
    partial class IdentitySagaDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppyNox.Services.Sso.Infrastructure.MassTransit.Sagas.UserCreationSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CorrelationId");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ConfirmPassword");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("CurrentState");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("LicenseId");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LicenseKey");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("CorrelationId");

                    b.ToTable("UserCreationSagaState", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
