version: '3.4'

networks:
  dev:
    driver: bridge


services:
 coupon-service:
   image: coupon-service:latest
   depends_on:
     - "postgres"
   ports:
     - "7001:7001"
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_URLS=https://+:7001
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/coupon-service.pfx 
     - ASPNETCORE_Kestrel__Certificates__Default__Password=happi2023
     - ConnectionStrings__DefaultConnection=User ID=postgres;Password=coupon_password;Server=postgres;Port=5432;Database=AppyNox_Coupon;IntegratedSecurity=true;Pooling=true
   volumes:
     - ./AppyNox.Services.Coupon.WebAPI/ssl:/https
   networks:
     - dev

 postgres:
   image: postgres:latest
   environment:
     POSTGRES_DB: AppyNox_Coupon
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: coupon_password
   restart: always
   ports:
     - "5433:5432"
   volumes:
     - app_data:/var/lib/postgresql/data
   networks:
     - dev

volumes:
  app_data:
