// <auto-generated />
using System;
using AppyNox.Services.Coupon.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppyNox.Services.Coupon.Infrastructure.Migrations
{
    [DbContext(typeof(CouponDbContext))]
    [Migration("20240228013305_DbFix1")]
    partial class DbFix1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppyNox.Services.Coupon.Domain.Coupons.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("CouponDetailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Detail")
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("CouponDetailId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("594cf045-3a2b-46f5-99c9-1eb59f035db2"),
                            Code = "EXF50",
                            CouponDetailId = new Guid("ec80532f-58f0-4690-b40c-2133b067d5f2"),
                            Description = "Description",
                            Detail = "Detail1"
                        },
                        new
                        {
                            Id = new Guid("c386aec2-dfd2-4ea5-b878-8fe5632e2e40"),
                            Code = "EXF60",
                            CouponDetailId = new Guid("ec80532f-58f0-4690-b40c-2133b067d5f2"),
                            Description = "Description2",
                            Detail = "Detail2"
                        });
                });

            modelBuilder.Entity("AppyNox.Services.Coupon.Domain.Coupons.CouponDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CouponDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec80532f-58f0-4690-b40c-2133b067d5f2"),
                            Code = "EXD10",
                            Detail = "TestDetail"
                        });
                });

            modelBuilder.Entity("AppyNox.Services.Coupon.Domain.Coupons.CouponDetailTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponDetailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CouponDetailId");

                    b.ToTable("CouponDetailTags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6bcfe76-83c7-4a4a-b088-13b14751fce8"),
                            CouponDetailId = new Guid("ec80532f-58f0-4690-b40c-2133b067d5f2"),
                            Tag = "Tag Description"
                        });
                });

            modelBuilder.Entity("AppyNox.Services.Coupon.Domain.Coupons.Coupon", b =>
                {
                    b.HasOne("AppyNox.Services.Coupon.Domain.Coupons.CouponDetail", "CouponDetail")
                        .WithMany("Coupons")
                        .HasForeignKey("CouponDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("AppyNox.Services.Coupon.Domain.Coupons.Amount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid");

                            b1.Property<double>("DiscountAmount")
                                .HasColumnType("double precision");

                            b1.Property<int>("MinAmount")
                                .HasColumnType("integer");

                            b1.HasKey("CouponId");

                            b1.ToTable("Coupons");

                            b1.WithOwner()
                                .HasForeignKey("CouponId");

                            b1.HasData(
                                new
                                {
                                    CouponId = new Guid("594cf045-3a2b-46f5-99c9-1eb59f035db2"),
                                    DiscountAmount = 10.65,
                                    MinAmount = 100
                                },
                                new
                                {
                                    CouponId = new Guid("c386aec2-dfd2-4ea5-b878-8fe5632e2e40"),
                                    DiscountAmount = 10.65,
                                    MinAmount = 100
                                });
                        });

                    b.OwnsOne("AppyNox.Services.Base.Domain.Interfaces.NoxAuditData", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("UpdateDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CouponId");

                            b1.ToTable("Coupons");

                            b1.WithOwner()
                                .HasForeignKey("CouponId");

                            b1.HasData(
                                new
                                {
                                    CouponId = new Guid("594cf045-3a2b-46f5-99c9-1eb59f035db2"),
                                    CreatedBy = "admin",
                                    CreationDate = new DateTime(2024, 2, 28, 1, 33, 4, 977, DateTimeKind.Utc).AddTicks(3036),
                                    UpdatedBy = ""
                                },
                                new
                                {
                                    CouponId = new Guid("c386aec2-dfd2-4ea5-b878-8fe5632e2e40"),
                                    CreatedBy = "admin",
                                    CreationDate = new DateTime(2024, 2, 28, 1, 33, 4, 977, DateTimeKind.Utc).AddTicks(3294),
                                    UpdatedBy = ""
                                });
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("CouponDetail");
                });

            modelBuilder.Entity("AppyNox.Services.Coupon.Domain.Coupons.CouponDetail", b =>
                {
                    b.OwnsOne("AppyNox.Services.Base.Domain.Interfaces.NoxAuditData", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CouponDetailId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("UpdateDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CouponDetailId");

                            b1.ToTable("CouponDetails");

                            b1.WithOwner()
                                .HasForeignKey("CouponDetailId");

                            b1.HasData(
                                new
                                {
                                    CouponDetailId = new Guid("ec80532f-58f0-4690-b40c-2133b067d5f2"),
                                    CreatedBy = "admin",
                                    CreationDate = new DateTime(2024, 2, 28, 1, 33, 4, 987, DateTimeKind.Utc).AddTicks(8101),
                                    UpdatedBy = ""
                                });
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("AppyNox.Services.Coupon.Domain.Coupons.CouponDetailTag", b =>
                {
                    b.HasOne("AppyNox.Services.Coupon.Domain.Coupons.CouponDetail", "CouponDetail")
                        .WithMany("CouponDetailTags")
                        .HasForeignKey("CouponDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AppyNox.Services.Base.Domain.Interfaces.NoxAuditData", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CouponDetailTagId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("UpdateDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CouponDetailTagId");

                            b1.ToTable("CouponDetailTags");

                            b1.WithOwner()
                                .HasForeignKey("CouponDetailTagId");

                            b1.HasData(
                                new
                                {
                                    CouponDetailTagId = new Guid("b6bcfe76-83c7-4a4a-b088-13b14751fce8"),
                                    CreatedBy = "admin",
                                    CreationDate = new DateTime(2024, 2, 28, 1, 33, 4, 992, DateTimeKind.Utc).AddTicks(2868),
                                    UpdatedBy = ""
                                });
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("CouponDetail");
                });

            modelBuilder.Entity("AppyNox.Services.Coupon.Domain.Coupons.CouponDetail", b =>
                {
                    b.Navigation("CouponDetailTags");

                    b.Navigation("Coupons");
                });
#pragma warning restore 612, 618
        }
    }
}
