name: AppyNox CI (SingleStep)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup SSL Certificates for Services
        run: |
          mkdir -p ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl
          echo '${{ secrets.PFX_CERTIFICATE }}' | base64 --decode > ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/appynox.pfx
          echo '${{ secrets.CRT_CERTIFICATE }}' | base64 --decode > ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/appynox.crt
          sudo chmod 644 ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/appynox.pfx
          sudo chmod 644 ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/appynox.crt

      - name: Restore dependencies
        run: dotnet restore ./AppyNox.sln

      - name: Build .NET Solution
        run: dotnet build ./AppyNox.sln --configuration Release --no-restore

      - name: Trust self-signed certificate
        run: |
          echo "${{ secrets.CRT_CERTIFICATE }}" | base64 --decode > appynox.crt
          sudo cp appynox.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates

      - name: Verify Trusted Certificates
        run: |
          echo "Listing trusted certificates:"
          sudo ls -l /etc/ssl/certs/ | grep appynox
          sudo openssl x509 -in /usr/local/share/ca-certificates/appynox.crt -text -noout

      - name: Create Redis ACL file
        run: echo '${{ secrets.REDIS_ACL }}' > ./redis.acl

      - name: Build Docker Images
        run: docker compose build

      - name: Create Docker Network
        run: docker network create nox_network

      - name: Start the Sso Container
        run: docker compose up -d

      - name: Wait for the Sso to Start
        run: sleep 120 

      - name: Log Containers in nox_network
        run: docker network inspect nox_network -f '{{json .Containers}}' | jq '.[].Name'

      - name: List All Containers
        run: docker ps


      - name: Get Container ID2
        id: get_container_id2
        run: echo "::set-output name=cid::$(docker ps -q -f name=appynox-services-sso-webapi)"


      - name: Print Container Logs
        run: docker logs ${{ steps.get_container_id2.outputs.cid }}


      - name: Test SSL Connection
        run: |
          retries=5
          until curl -v http://appynox-services-sso-webapi:7001/api/health || [ $retries -eq 0 ]; do
            echo "Waiting for the SSO service to be ready..."
            retries=$((retries-1))
            sleep 10
          done

      - name: Test SSL Connection from Runner
        run: curl -v https://localhost:7000/sso-service/health

      - name: Run Integration Tests (SsoService)
        run: dotnet test ./src/Services/SsoService/Tests/IntegrationTests/AppyNox.Services.Sso.WebAPI.IntegrationTest --no-restore

      - name: Restore dependencies
        run: dotnet restore ./AppyNox.sln

      - name: Build .NET Solution
        run: dotnet build ./AppyNox.sln --configuration Release --no-restore

      - name: Run Unit Tests (BaseService - Infrastructure)
        run: dotnet test ./src/Services/.BaseService/Tests/UnitTests/AppyNox.Services.Base.Infrastructure.UnitTest/ --no-restore

      - name: Run Unit Tests (CouponService - Infrastructure)
        run: dotnet test ./src/Services/CouponService/Tests/UnitTests/AppyNox.Services.Coupon.Infrastructure.UnitTest/ --no-restore

      - name: Run Unit Tests (CouponService - Application)
        run: dotnet test ./src/Services/CouponService/Tests/UnitTests/AppyNox.Services.Coupon.Application.UnitTest/ --no-restore

      - name: Run Unit Tests (LicenseService - Infrastructure)
        run: dotnet test ./src/Services/LicenseService/Tests/UnitTests/AppyNox.Services.License.Infrastructure.UnitTest/ --no-restore

      - name: Run Unit Tests (LicenseService - Application)
        run: dotnet test ./src/Services/LicenseService/Tests/UnitTests/AppyNox.Services.License.Application.UnitTest/ --no-restore

      - name: Run Unit Tests (SsoService - Application)
        run: dotnet test ./src/Services/SsoService/Tests/UnitTests/AppyNox.Services.Sso.Application.UnitTest/ --no-restore

      - name: Run Unit Tests (SsoService - WebAPI)
        run: dotnet test ./src/Services/SsoService/Tests/UnitTests/AppyNox.Services.Sso.WebAPI.UnitTest/ --no-restore 

      - name: Trust self-signed certificate
        run: |
          echo "${{ secrets.PFX_CERTIFICATE }}" | base64 --decode > appynox_staging.pfx
          # Extract the certificate from the .pfx file
          openssl pkcs12 -in appynox_staging.pfx -clcerts -nokeys -out appynox_staging.crt -password pass:${{ secrets.PFX_PASSWORD }}
          # Trust the certificate
          sudo cp appynox_staging.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates

      - name: Create Redis ACL file
        run: echo '${{ secrets.REDIS_ACL }}' > ./redis.acl

      - name: Build Docker Images
        run: docker compose build

      - name: Run Integration Tests (SsoService)
        run: dotnet test ./src/Services/SsoService/Tests/IntegrationTests/AppyNox.Services.Sso.WebAPI.IntegrationTest --no-restore

      - name: Run Integration Tests (CouponService)
        run: dotnet test ./src/Services/CouponService/Tests/IntegrationTests/AppyNox.Services.Coupon.WebAPI.IntegrationTest --no-restore

      - name: Run Integration Tests (LicenseService)
        run: dotnet test ./src/Services/LicenseService/Tests/IntegrationTests/AppyNox.Services.License.WebAPI.IntegrationTest --no-restore  
