name: AppyNox CI (SingleStep)

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup SSL Certificates for Services
        run: |
          mkdir -p ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl
          echo '${{ secrets.PFX_CERTIFICATE }}' | base64 --decode > ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/appynox.pfx
          echo '${{ secrets.CRT_CERTIFICATE }}' | base64 --decode > ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/appynox.crt
          sudo chmod 644 ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/appynox.pfx
          sudo chmod 644 ./src/Gateways/AppyNox.Gateway.OcelotGateway/ssl/appynox.crt

      - name: Restore dependencies
        run: dotnet restore ./AppyNox.sln

      - name: Build .NET Solution
        run: dotnet build ./AppyNox.sln --configuration Release --no-restore

      - name: Trust self-signed certificate
        run: |
          echo "${{ secrets.CRT_CERTIFICATE }}" | base64 --decode > appynox.crt
          sudo cp appynox.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates

      - name: Verify Trusted Certificates
        run: |
          echo "Listing trusted certificates:"
          sudo ls -l /etc/ssl/certs/ | grep appynox
          sudo openssl x509 -in /usr/local/share/ca-certificates/appynox.crt -text -noout

      # - name: Create Redis ACL file
      #   run: echo '${{ secrets.REDIS_ACL }}' > ./redis.acl

      - name: Build Docker Images
        run: docker compose build

      - name: Run Integration Tests (SsoService)
        run: dotnet test ./src/Services/SsoService/Tests/IntegrationTests/AppyNox.Services.Sso.WebAPI.IntegrationTest --no-restore

      - name: Run Integration Tests (CouponService)
        run: dotnet test ./src/Services/CouponService/Tests/IntegrationTests/AppyNox.Services.Coupon.WebAPI.IntegrationTest --no-restore

      - name: Run Integration Tests (LicenseService)
        run: dotnet test ./src/Services/LicenseService/Tests/IntegrationTests/AppyNox.Services.License.WebAPI.IntegrationTest --no-restore  
