name: .NET Microservices CI

on:
  push:
    branches: [ AppyNox-70 ]
  pull_request:
    branches: [ AppyNox-70 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker Images
      run: docker-compose -f docker-compose.yml -f docker-compose.development.yml build

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./AppyNox.sln

    - name: Run Unit Tests
      run: dotnet test ./src/Services/CouponService/Tests/UnitTests/AppyNox.Services.Coupon.Infrastructure.UnitTest/ --no-restore

    #- name: Run Integration Tests
     # run: dotnet test <path-to-your-integration-test-project> --no-restore

    # Optional: Add steps for pushing to Docker registry or deploying to Docker Swarm
