name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly at midnight on Sunday
  workflow_dispatch: # Allows manual trigger

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
