name: Deploy Docsify Documentation

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Docsify to GitHub Pages
      uses: tool3/docsify-action@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
