name: PR Checks

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./AppyNox.sln

      - name: Build .NET Solution
        run: dotnet build ./AppyNox.sln --configuration Release --no-restore

      - name: Cache .NET packages
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-packages-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-packages-

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service:
          - { name: "BaseService", path: "./src/Services/.BaseService/Tests/UnitTests/AppyNox.Services.Base.Infrastructure.UnitTest/" }
          - { name: "CouponService - Infrastructure", path: "./src/Services/CouponService/Tests/UnitTests/AppyNox.Services.Coupon.Infrastructure.UnitTest/" }
          - { name: "CouponService - Application", path: "./src/Services/CouponService/Tests/UnitTests/AppyNox.Services.Coupon.Application.UnitTest/" }
          - { name: "LicenseService - Infrastructure", path: "./src/Services/LicenseService/Tests/UnitTests/AppyNox.Services.License.Infrastructure.UnitTest/" }
          - { name: "LicenseService - Application", path: "./src/Services/LicenseService/Tests/UnitTests/AppyNox.Services.License.Application.UnitTest/" }
          - { name: "SsoService - Application", path: "./src/Services/SsoService/Tests/UnitTests/AppyNox.Services.Sso.Application.UnitTest/" }
          - { name: "SsoService - WebAPI", path: "./src/Services/SsoService/Tests/UnitTests/AppyNox.Services.Sso.WebAPI.UnitTest/" }

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Unit Tests for ${{ matrix.service.name }}
        run: dotnet test ${{ matrix.service.path }}
