name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow when you push tags like v1.0.0
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # Restore Dependencies
      - name: Restore dependencies for BaseService API
        run: dotnet restore ./src/Services/.BaseService/AppyNox.Services.Base.API/AppyNox.Services.Base.API.csproj

      - name: Restore dependencies for BaseService Application
        run: dotnet restore ./src/Services/.BaseService/AppyNox.Services.Base.Application/AppyNox.Services.Base.Application.csproj

      - name: Restore dependencies for BaseService Domain
        run: dotnet restore ./src/Services/.BaseService/AppyNox.Services.Base.Domain/AppyNox.Services.Base.Domain.csproj

      - name: Restore dependencies for BaseService Infrastructure
        run: dotnet restore ./src/Services/.BaseService/AppyNox.Services.Base.Infrastructure/AppyNox.Services.Base.Infrastructure.csproj

      # Build
      - name: Build BaseService API
        run: dotnet build ./src/Services/.BaseService/AppyNox.Services.Base.API/AppyNox.Services.Base.API.csproj --configuration Release --no-restore

      - name: Build BaseService Application
        run: dotnet build ./src/Services/.BaseService/AppyNox.Services.Base.Application/AppyNox.Services.Base.Application.csproj --configuration Release --no-restore

      - name: Build BaseService Domain
        run: dotnet build ./src/Services/.BaseService/AppyNox.Services.Base.Domain/AppyNox.Services.Base.Domain.csproj --configuration Release --no-restore

      - name: Build BaseService Infrastructure
        run: dotnet build ./src/Services/.BaseService/AppyNox.Services.Base.Infrastructure/AppyNox.Services.Base.Infrastructure.csproj --configuration Release --no-restore

      # Pack
      - name: Pack BaseService API
        run: dotnet pack ./src/Services/.BaseService/AppyNox.Services.Base.API/AppyNox.Services.Base.API.csproj --configuration Release --no-build --output ../../nupkgs

      - name: Pack BaseService Application
        run: dotnet pack ./src/Services/.BaseService/AppyNox.Services.Base.Application/AppyNox.Services.Base.Application.csproj --configuration Release --no-build --output ../../nupkgs

      - name: Pack BaseService Domain
        run: dotnet pack ./src/Services/.BaseService/AppyNox.Services.Base.Domain/AppyNox.Services.Base.Domain.csproj --configuration Release --no-build --output ../../nupkgs

      - name: Pack BaseService Infrastructure
        run: dotnet pack ./src/Services/.BaseService/AppyNox.Services.Base.Infrastructure/AppyNox.Services.Base.Infrastructure.csproj --configuration Release --no-build --output ../../nupkgs

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "github" --api-key ${{ secrets.NUGET_API_KEY }}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY_ORG }}
