name: Publish NuGet Package

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # This will trigger the workflow when you push tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack BaseService API
        run: dotnet pack ./src/Services/BaseService/AppyNox.Services.Base.API --configuration Release --output ./nupkgs

      - name: Pack BaseService Application
        run: dotnet pack ./src/Services/BaseService/AppyNox.Services.Base.Application --configuration Release --output ./nupkgs

      - name: Pack BaseService Domain
        run: dotnet pack ./src/Services/BaseService/AppyNox.Services.Base.Domain --configuration Release --output ./nupkgs

      - name: Pack BaseService Infrastructure
        run: dotnet pack ./src/Services/BaseService/AppyNox.Services.Base.Infrastructure --configuration Release --output ./nupkgs

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "github" --api-key ${{ secrets.NUGET_API_KEY }}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY_ORG }}
