name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow when you push tags like v1.0.0
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # Restore Dependencies
      - name: Restore dependencies for BaseService API
        run: dotnet restore ./src/Services/.BaseService/AppyNox.Services.Base.API/AppyNox.Services.Base.API.csproj

      - name: Restore dependencies for BaseService Application
        run: dotnet restore ./src/Services/.BaseService/AppyNox.Services.Base.Application/AppyNox.Services.Base.Application.csproj

      - name: Restore dependencies for BaseService Domain
        run: dotnet restore ./src/Services/.BaseService/AppyNox.Services.Base.Domain/AppyNox.Services.Base.Domain.csproj

      - name: Restore dependencies for BaseService Infrastructure
        run: dotnet restore ./src/Services/.BaseService/AppyNox.Services.Base.Infrastructure/AppyNox.Services.Base.Infrastructure.csproj

      - name: Restore dependencies for BaseService Application UnitTests
        run: dotnet restore ./src/Services/.BaseService/Tests/UnitTests/AppyNox.Services.Base.Application.UnitTests/AppyNox.Services.Base.Application.UnitTests.csproj

      - name: Restore dependencies for BaseService Infrastructure UnitTests
        run: dotnet restore ./src/Services/.BaseService/Tests/UnitTests/AppyNox.Services.Base.Infrastructure.UnitTests/AppyNox.Services.Base.Infrastructure.UnitTests.csproj

      - name: Restore dependencies for BaseService IntegrationTests
        run: dotnet restore ./src/Services/.BaseService/Tests/IntegrationTests/AppyNox.Services.Base.IntegrationTests/AppyNox.Services.Base.IntegrationTests.csproj

      - name: Restore dependencies for SsoService Public Contracts
        run: dotnet restore ./src/Services/SsoService/AppyNox.Services.Sso.Contracts.Public/AppyNox.Services.Sso.Contracts.Public.csproj

      # Build
      - name: Build BaseService Core
        run: dotnet build ./src/Services/.BaseService/AppyNox.Services.Base.Core/AppyNox.Services.Base.Core.csproj --configuration Release --no-restore

      - name: Build BaseService Domain
        run: dotnet build ./src/Services/.BaseService/AppyNox.Services.Base.Domain/AppyNox.Services.Base.Domain.csproj --configuration Release --no-restore

      - name: Build BaseService Application
        run: dotnet build ./src/Services/.BaseService/AppyNox.Services.Base.Application/AppyNox.Services.Base.Application.csproj --configuration Release --no-restore

      - name: Build BaseService Infrastructure
        run: dotnet build ./src/Services/.BaseService/AppyNox.Services.Base.Infrastructure/AppyNox.Services.Base.Infrastructure.csproj --configuration Release --no-restore

      - name: Build BaseService API
        run: dotnet build ./src/Services/.BaseService/AppyNox.Services.Base.API/AppyNox.Services.Base.API.csproj --configuration Release --no-restore

      - name: Build for BaseService Application UnitTests
        run: dotnet build ./src/Services/.BaseService/Tests/UnitTests/AppyNox.Services.Base.Application.UnitTests/AppyNox.Services.Base.Application.UnitTests.csproj --configuration Release --no-restore

      - name: Build for BaseService Infrastructure UnitTests
        run: dotnet build ./src/Services/.BaseService/Tests/UnitTests/AppyNox.Services.Base.Infrastructure.UnitTests/AppyNox.Services.Base.Infrastructure.UnitTests.csproj --configuration Release --no-restore

      - name: Build for BaseService IntegrationTests
        run: dotnet build ./src/Services/.BaseService/Tests/IntegrationTests/AppyNox.Services.Base.IntegrationTests/AppyNox.Services.Base.IntegrationTests.csproj --configuration Release --no-restore

      - name: Build dependencies for SsoService Public Contracts
        run: dotnet build ./src/Services/SsoService/AppyNox.Services.Sso.Contracts.Public/AppyNox.Services.Sso.Contracts.Public.csproj --configuration Release --no-restore

      # Pack
      - name: Pack BaseService Core
        run: dotnet pack ./src/Services/.BaseService/AppyNox.Services.Base.Core/AppyNox.Services.Base.Core.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack BaseService Domain
        run: dotnet pack ./src/Services/.BaseService/AppyNox.Services.Base.Domain/AppyNox.Services.Base.Domain.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack BaseService Infrastructure
        run: dotnet pack ./src/Services/.BaseService/AppyNox.Services.Base.Infrastructure/AppyNox.Services.Base.Infrastructure.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack BaseService Application
        run: dotnet pack ./src/Services/.BaseService/AppyNox.Services.Base.Application/AppyNox.Services.Base.Application.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack BaseService API
        run: dotnet pack ./src/Services/.BaseService/AppyNox.Services.Base.API/AppyNox.Services.Base.API.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack for BaseService Application UnitTests
        run: dotnet pack ./src/Services/.BaseService/Tests/UnitTests/AppyNox.Services.Base.Application.UnitTests/AppyNox.Services.Base.Application.UnitTests.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack for BaseService Infrastructure UnitTests
        run: dotnet pack ./src/Services/.BaseService/Tests/UnitTests/AppyNox.Services.Base.Infrastructure.UnitTests/AppyNox.Services.Base.Infrastructure.UnitTests.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack for BaseService IntegrationTests
        run: dotnet pack ./src/Services/.BaseService/Tests/IntegrationTests/AppyNox.Services.Base.IntegrationTests/AppyNox.Services.Base.IntegrationTests.csproj --configuration Release --no-build --output ./nupkgs

      - name: Pack dependencies for SsoService Public Contracts
        run: dotnet pack ./src/Services/SsoService/AppyNox.Services.Sso.Contracts.Public/AppyNox.Services.Sso.Contracts.Public.csproj --configuration Release --no-build --output ./nupkgs


     # Publish both regular NuGet packages and symbol packages
      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/HappiSoftware/index.json" --api-key ${{ secrets.NUGET_API_KEY_ORG }}

